repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.7
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|h|hpp|cu|cuh)$
